import { Framework, WizardResult } from '../types/framework';
import { Language } from '../i18n/types';

export function generateMarkdownReport(result: WizardResult, lang: Language = 'vi'): string {
  const fw = result.topFramework;
  const dateStr = new Date().toISOString().split('T')[0];

  if (lang === 'vi') {
    return `# Báo Cáo Chẩn Đoán Phương Pháp Luận Giải Quyết Vấn Đề
Ngày lập: ${dateStr}

## 🎯 Phương Pháp Khuyến Nghị Tối Ưu: ${fw.name} (Độ tương thích: ${result.topScore}%)
**Xuất xứ:** ${fw.origin}  
**Nhóm phân loại:** ${fw.category.toUpperCase()} | **Độ phức tạp:** ${fw.complexity} | **Thời gian:** ${fw.timeframe} | **Quy mô nhóm:** ${fw.teamSize}  
**Miền không gian Cynefin:** ${fw.cynefinDomain}

> "${fw.tagline}"

### 💡 Lý Do Phù Hợp Với Bài Toán Của Bạn:
${result.matchReason}

### 🎯 Ứng Dụng Tốt Nhất Khi:
${fw.bestFor}

### ⚠️ Cần Tránh Khi:
${fw.whenToAvoid}

---

## 🛠️ Cẩm Nang Thực Thi Từng Bước

${fw.steps.map(s => `### Bước ${s.number}: ${s.title}
${s.description}
*Mẹo thực chiến:* ${s.actionableTip}
`).join('\n')}

---

## 🔍 Các Câu Hỏi Gợi Ý Chẩn Đoán
${fw.keyQuestions.map(q => `- [ ] ${q}`).join('\n')}

---

## 🏢 Tình Huống Thực Tế Điển Hình: ${fw.exampleUseCase.title}
- **Bối cảnh:** ${fw.exampleUseCase.scenario}
- **Cách áp dụng:** ${fw.exampleUseCase.application}
- **Kết quả đo lường được:** ${fw.exampleUseCase.outcome}

---

## 🔄 Các Lựa Chọn Thay Thế Khả Thi
${result.runnerUps.map(r => `1. **${r.framework.name}** (${r.score}%): ${r.fitReason}`).join('\n')}

${result.avoidFrameworks.length > 0 ? `
---

## ⛔ Các Phương Pháp Nên Tránh Trong Bối Cảnh Này
${result.avoidFrameworks.map(a => `- **${a.framework.name}**: ${a.reason}`).join('\n')}
` : ''}

*Báo cáo được khởi tạo từ Problem-Solving Framework Chooser*
`;
  }

  return `# Problem-Solving Framework Diagnostic Report
Generated on: ${dateStr}

## 🎯 Recommended Primary Framework: ${fw.name} (${result.topScore}% Match)
**Origin:** ${fw.origin}  
**Category:** ${fw.category.toUpperCase()} | **Complexity:** ${fw.complexity} | **Timeframe:** ${fw.timeframe} | **Team:** ${fw.teamSize}  
**Cynefin Domain:** ${fw.cynefinDomain}

> "${fw.tagline}"

### 💡 Why This Fits Your Challenge:
${result.matchReason}

### 🎯 Best For:
${fw.bestFor}

### ⚠️ When to Avoid:
${fw.whenToAvoid}

---

## 🛠️ Step-by-Step Execution Playbook

${fw.steps.map(s => `### Step ${s.number}: ${s.title}
${s.description}
*Pro-tip:* ${s.actionableTip}
`).join('\n')}

---

## 🔍 Diagnostic Guiding Questions
${fw.keyQuestions.map(q => `- [ ] ${q}`).join('\n')}

---

## 🏢 Real-World Case Study: ${fw.exampleUseCase.title}
- **Scenario:** ${fw.exampleUseCase.scenario}
- **Execution:** ${fw.exampleUseCase.application}
- **Outcome:** ${fw.exampleUseCase.outcome}

---

## 🔄 Viable Runner-Up Alternatives
${result.runnerUps.map(r => `1. **${r.framework.name}** (${r.score}% Match): ${r.fitReason}`).join('\n')}

${result.avoidFrameworks.length > 0 ? `
---

## ⛔ Frameworks to Explicitly Avoid in This Context
${result.avoidFrameworks.map(a => `- **${a.framework.name}**: ${a.reason}`).join('\n')}
` : ''}

*Report generated by Problem-Solving Framework Chooser*
`;
}

export function generateFrameworkMarkdown(fw: Framework, lang: Language = 'vi'): string {
  if (lang === 'vi') {
    return `# Cẩm Nang Phương Pháp: ${fw.name}
**Khẩu hiệu:** ${fw.tagline}  
**Xuất xứ:** ${fw.origin}  
**Phân loại:** ${fw.category} | **Độ phức tạp:** ${fw.complexity} | **Thời gian:** ${fw.timeframe} | **Nhóm:** ${fw.teamSize}

## Tổng Quan
${fw.summary}

## Phù Hợp Nhất Khi:
${fw.bestFor}

## Tránh Sử Dụng Khi:
${fw.whenToAvoid}

## Các Bước Thực Hiện:
${fw.steps.map(s => `### Bước ${s.number}: ${s.title}\n${s.description}\n*Mẹo:* ${s.actionableTip}\n`).join('\n')}

## Câu Hỏi Chẩn Đoán:
${fw.keyQuestions.map(q => `- ${q}`).join('\n')}

## Ví Dụ Thực Tế: ${fw.exampleUseCase.title}
- **Bối cảnh:** ${fw.exampleUseCase.scenario}
- **Phương pháp:** ${fw.exampleUseCase.application}
- **Kết quả:** ${fw.exampleUseCase.outcome}

## Ưu & Nhược Điểm:
### Điểm mạnh:
${fw.pros.map(p => `+ ${p}`).join('\n')}

### Hạn chế:
${fw.cons.map(c => `- ${c}`).join('\n')}
`;
  }

  return `# Framework Playbook: ${fw.name}
**Tagline:** ${fw.tagline}  
**Origin:** ${fw.origin}  
**Category:** ${fw.category} | **Complexity:** ${fw.complexity} | **Timeframe:** ${fw.timeframe} | **Team:** ${fw.teamSize}

## Overview
${fw.summary}

## Best Applied In:
${fw.bestFor}

## Avoid When:
${fw.whenToAvoid}

## Execution Steps:
${fw.steps.map(s => `### Step ${s.number}: ${s.title}\n${s.description}\n*Tip:* ${s.actionableTip}\n`).join('\n')}

## Diagnostic Questions:
${fw.keyQuestions.map(q => `- ${q}`).join('\n')}

## Real-World Example: ${fw.exampleUseCase.title}
- **Scenario:** ${fw.exampleUseCase.scenario}
- **Method:** ${fw.exampleUseCase.application}
- **Result:** ${fw.exampleUseCase.outcome}

## Pros & Cons:
### Pros:
${fw.pros.map(p => `+ ${p}`).join('\n')}

### Cons:
${fw.cons.map(c => `- ${c}`).join('\n')}
`;
}

export function copyToClipboard(text: string): Promise<boolean> {
  if (navigator.clipboard && window.isSecureContext) {
    return navigator.clipboard.writeText(text).then(() => true).catch(() => false);
  } else {
    const textArea = document.createElement('textarea');
    textArea.value = text;
    textArea.style.position = 'fixed';
    textArea.style.left = '-999999px';
    textArea.style.top = '-999999px';
    document.body.appendChild(textArea);
    textArea.focus();
    textArea.select();
    try {
      document.execCommand('copy');
      textArea.remove();
      return Promise.resolve(true);
    } catch {
      textArea.remove();
      return Promise.resolve(false);
    }
  }
}

export function downloadFile(filename: string, content: string, mimeType = 'text/markdown') {
  const blob = new Blob([content], { type: mimeType });
  const url = URL.createObjectURL(blob);
  const link = document.createElement('a');
  link.href = url;
  link.download = filename;
  document.body.appendChild(link);
  link.click();
  document.body.removeChild(link);
  URL.revokeObjectURL(url);
}
