import { Framework, WizardResult } from '../types/framework';

export function generateMarkdownReport(result: WizardResult): string {
  const fw = result.topFramework;
  const dateStr = new Date().toISOString().split('T')[0];

  return `# Problem-Solving Framework Diagnostic Report
Generated on: ${dateStr}

## 🎯 Recommended Primary Framework: ${fw.name} (${result.topScore}% Match)
**Origin:** ${fw.origin}  
**Category:** ${fw.category.toUpperCase()} | **Complexity:** ${fw.complexity} | **Timeframe:** ${fw.timeframe} | **Team:** ${fw.teamSize}  
**Cynefin Domain:** ${fw.cynefinDomain}

> "${fw.tagline}"

### 💡 Why This Fits Your Challenge:
${result.matchReason}

### 🎯 Best For:
${fw.bestFor}

### ⚠️ When to Avoid:
${fw.whenToAvoid}

---

## 🛠️ Step-by-Step Execution Playbook

${fw.steps.map(s => `### Step ${s.number}: ${s.title}
${s.description}
*Pro-tip:* ${s.actionableTip}
`).join('\n')}

---

## 🔍 Diagnostic Guiding Questions
${fw.keyQuestions.map(q => `- [ ] ${q}`).join('\n')}

---

## 🏢 Real-World Case Study: ${fw.exampleUseCase.title}
- **Scenario:** ${fw.exampleUseCase.scenario}
- **Execution:** ${fw.exampleUseCase.application}
- **Outcome:** ${fw.exampleUseCase.outcome}

---

## 🔄 Viable Runner-Up Alternatives
${result.runnerUps.map(r => `1. **${r.framework.name}** (${r.score}% Match): ${r.fitReason}`).join('\n')}

${result.avoidFrameworks.length > 0 ? `
---

## ⛔ Frameworks to Explicitly Avoid in This Context
${result.avoidFrameworks.map(a => `- **${a.framework.name}**: ${a.reason}`).join('\n')}
` : ''}

*Report generated by Problem-Solving Framework Chooser*
`;
}

export function generateFrameworkMarkdown(fw: Framework): string {
  return `# Framework Playbook: ${fw.name}
**Tagline:** ${fw.tagline}  
**Origin:** ${fw.origin}  
**Category:** ${fw.category} | **Complexity:** ${fw.complexity} | **Timeframe:** ${fw.timeframe} | **Team:** ${fw.teamSize}

## Overview
${fw.summary}

## Best Applied In:
${fw.bestFor}

## Avoid When:
${fw.whenToAvoid}

## Execution Steps:
${fw.steps.map(s => `### Step ${s.number}: ${s.title}\n${s.description}\n*Tip:* ${s.actionableTip}\n`).join('\n')}

## Diagnostic Questions:
${fw.keyQuestions.map(q => `- ${q}`).join('\n')}

## Real-World Example: ${fw.exampleUseCase.title}
- **Scenario:** ${fw.exampleUseCase.scenario}
- **Method:** ${fw.exampleUseCase.application}
- **Result:** ${fw.exampleUseCase.outcome}

## Pros & Cons:
### Pros:
${fw.pros.map(p => `+ ${p}`).join('\n')}

### Cons:
${fw.cons.map(c => `- ${c}`).join('\n')}
`;
}

export function copyToClipboard(text: string): Promise<boolean> {
  if (navigator.clipboard && window.isSecureContext) {
    return navigator.clipboard.writeText(text).then(() => true).catch(() => false);
  } else {
    const textArea = document.createElement('textarea');
    textArea.value = text;
    textArea.style.position = 'fixed';
    textArea.style.left = '-999999px';
    textArea.style.top = '-999999px';
    document.body.appendChild(textArea);
    textArea.focus();
    textArea.select();
    try {
      document.execCommand('copy');
      textArea.remove();
      return Promise.resolve(true);
    } catch {
      textArea.remove();
      return Promise.resolve(false);
    }
  }
}

export function downloadFile(filename: string, content: string, mimeType = 'text/markdown') {
  const blob = new Blob([content], { type: mimeType });
  const url = URL.createObjectURL(blob);
  const link = document.createElement('a');
  link.href = url;
  link.download = filename;
  document.body.appendChild(link);
  link.click();
  document.body.removeChild(link);
  URL.revokeObjectURL(url);
}
